import type { ScanRule } from "./scan-types.js";

export const SCAN_RULES: readonly ScanRule[] = [
  {
    id: "dangerous-exec",
    severity: "critical",
    description: "Shell command execution detected",
    type: "line",
    pattern: /\b(exec|execSync|spawn|spawnSync|execFile)\s*\(/,
    context: /child_process/,
    contextType: "import",
  },
  {
    id: "dynamic-eval",
    severity: "critical",
    description: "Dynamic code execution (eval/Function constructor)",
    type: "line",
    pattern: /\beval\s*\(|new\s+Function\s*\(/,
  },
  {
    id: "crypto-mining",
    severity: "critical",
    description: "Cryptocurrency mining signatures",
    type: "line",
    pattern: /stratum\+tcp|coinhive|cryptonight|xmrig/i,
  },
  {
    id: "env-harvesting",
    severity: "critical",
    description: "Environment variables accessed near network calls",
    type: "source",
    pattern: /process\.env/,
    context: /\bfetch\b|http\.request|https\.request|axios\b|got\(/,
    contextType: "source",
  },
  {
    id: "data-exfiltration",
    severity: "warn",
    description: "File read combined with network request",
    type: "source",
    pattern: /readFileSync|readFile|createReadStream/,
    context: /\bfetch\b|http\.request|https\.request/,
    contextType: "source",
  },
  {
    id: "obfuscated-code",
    severity: "warn",
    description: "Obfuscated code detected (hex/base64 sequences)",
    type: "line",
    pattern: /(\\x[0-9a-fA-F]{2}){6,}|atob\s*\(.*[A-Za-z0-9+/=]{200,}/,
  },
  {
    id: "suspicious-network",
    severity: "warn",
    description: "WebSocket connection to non-standard port",
    type: "line",
    pattern: /new\s+WebSocket\s*\(\s*['"`]wss?:\/\/[^'"]*:\d{4,5}/,
  },
  {
    id: "global-override",
    severity: "warn",
    description: "Global object or prototype manipulation",
    type: "line",
    pattern: /globalThis\s*[.[=]|Object\.defineProperty\s*\(\s*global/,
  },
  {
    id: "fs-write",
    severity: "info",
    description: "Filesystem write operations",
    type: "line",
    pattern: /writeFileSync|writeFile|appendFile|createWriteStream/,
  },
  {
    id: "dns-lookup",
    severity: "info",
    description: "DNS resolution calls",
    type: "line",
    pattern: /dns\.resolve|dns\.lookup|dns\.reverse/,
  },
] as const;
